### ISSUE TITLE
Pb avec l'affichage

### ISSUE THREAD

**Issue by thriant** [thriant/mini_jeu_POO#1]
``Traceback (most recent call last):
	1: from app_2.rb:40:in `<main>'
app_2.rb:31:in `menu_actions': undefined local variable or method `player1' for main:Object (NameError)``

Erreur étrange, je me torture un peu l'esprit à la comprendre...
Il est dit que ruby ne trouve pas la variable player 1 or elle est définie plus haut...

**Comment by thriant** [comment]
Résole
